language: node_js
node_js:
  - "5.1"
  - "4"
  - "iojs"
services:
- rabbitmq
- docker
before_install:
- docker run -d -p 127.0.0.1:30001:5672 webcenter/activemq
- docker run -d -p 127.0.0.1:11300:11300 schickling/beanstalkd
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
env:
- BEANSTALKD_HOST=localhost BEANSTALKD_PORT=11300 ACTIVEMQ_HOST=localhost ACTIVEMQ_PORT=30001
  ACTIVEMQ_USERNAME=admin ACTIVEMQ_PASSWORD=admin RABBITMQ_HOST=localhost RABBITMQ_PORT=5672
  RABBITMQ_USERNAME=guest RABBITMQ_PASSWORD=guest
after_success:
- npm install codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: ph.woerdehoff@gmail.com
  on:
    tags: true
    repo: 21stio/nodejs-queue-adapter
  api_key:
    secure: F2EdQbxwsoNq+t/LxHXeWZoEBNrRQA+rQfVi3J4pPVunMi9M2k+fhBDDGKP+inDKUT45sNULx8fYbErcSlXGPvqLaboWfVIsXgVVzDljGyddo8wMTtJUaUcvQ2l/CVxSeBwiIFedRBI+nPMZ5c4Te+LMrsX7MOAPD0Kp6WS4dOVQC6d70K0yc9Aj+CD+sZBuBDjd0JXDqs+GYENj3PBYNlTaVKs/AO7630LtUlT22RBsCI6zgQi8S7T3nRN64uuu3dp+0sMQUSoHYlq9dZUe5qAupvVNAlwdhJ7cHVrEukNJeFLse6AidIiDOA6TbuZQYQPJIDzljbtxVsYX2z8EbPn7hn9aFOAxGlc66KljdL6veipIbK/D3RMdcpZ+S3trrR026xAhQpXT6S6H09EBKJOR0gCQb+NP+xkolzCfkzoU/t1VcYZtlmvknCYfAdt5rXzz2yHP+xCk2AHIdWMqcloCd/kUIJfop89F2ycD00D268DDzlQxMle1Z5SQGpFVut+0wDwHAzFrV+LTBr/bQbAQTDQaUag9a3Oqfxup/xne/fYbHZPcrTUciErDAdGWvN+EwBlg+ZxnbqRoASnI/W5LduUOqMbCN1VNBqJcFYruNMk1knnsACZ6iqvVR5vQJScAfl4q7v+wczQZ73Kloc5aoO9S9KLARR8+SQt6Heo=
