language: node_js
node_js:
- '4.2'
services:
- rabbitmq
- docker
before_install:
- docker run -d -p 127.0.0.1:30001:5672 webcenter/activemq
- docker run -d -p 127.0.0.1:11300:11300 schickling/beanstalkd
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
- cat ~/.npmrc
env:
- BEANSTALKD_HOST=localhost BEANSTALKD_PORT=11300 ACTIVEMQ_HOST=localhost ACTIVEMQ_PORT=30001
  ACTIVEMQ_USERNAME=admin ACTIVEMQ_PASSWORD=admin RABBITMQ_HOST=localhost RABBITMQ_PORT=5672
  RABBITMQ_USERNAME=guest RABBITMQ_PASSWORD=guest
after_success:
- npm install codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: ph.woerdehoff@gmail.com
  on:
    tags: true
    repo: 21stio/nodejs-queue-adapter
  api_key:
    secure: oHGqw5ujM1TtV4wc60zxYuWeaEMMX+CWbLnzlrrNWC/m7wk+iQWRGjKSKWcVvR58Pkq0qX590ZQljnvWFoCUXPgkHvA26Pzp0UNTX1JB81ZY4HcxtImOgrQqG5SD3fwI4/vangua6vvg4OScvkId48YvauFbfu+2xg9sphQR7nDbq3+1g4WciVs6HIEPy84BqTQS7F0Du90cPjOgSbn43r5VSMRAwctG8CBeNirrWd7AeV5AAjBa21EXa1yvXu4+wia3wH3oLTFNV/VCZrwNsjJD7/0JltXu7smpkNcz6G/MyCPValloJLNCTA5LOa7nkiYcaP2RAbqq8iSdlS6GWgVdy9Id/2lHLdceORnRJMzMvUQ1a9ThtIlM3vfVakE6ZwoNBV7FxUBMWoV+Wp4OBLinSjGEsNSkj4PEtL3rUubLqmm8Lo3wI89gQU9RjtN722yZs2BlGELifj/KwNFS5hy1/jBeiGPg4ebDXcYruLujLn57wiPR4hGoYjQuiU6zlA+hmTH+wf7ziSZalqCRzURnFeUCaT66nBGFl7TIhn1mk3Z7ze3rOhQVB3YKpufexYGJ41R89DonD3ofL2IT52ghkpBqT8sU3RbAahKVtCuZJBDS8/4F+z/WHhN+V9WEhBLED6cZ/I/H1SB4Fe6p4kW/TDh9eNmNAtiKXDggCa8=
